### ISSUE TITLE
Suggestion -Create action to parse data from dssg-pt repository

### ISSUE THREAD

**Issue by Jpfonseca** [mjamado/covidConcelhos#2]
As the title specifies, the idea is to create an automatic action which will actualize the data folder by polling the information from the [Data Science for Social Good Portugal Covid-19 repository
](https://github.com/dssg-pt/covid19pt-data/blob/master/data_concelhos.csv).

**Comment by mjamado** [comment]
Good idea.

Will try to make that happen next week.

This project is semi-abandoned, because DGS stopped releasing municipality data on a daily basis, but at least with this change I won't get as frustrated with the lack of data.

**Comment by mjamado** [comment]
Closed by f884bee021574e6a960cf3bb8f6f34db65ac791c.

**Comment by mjamado** [comment]
I had to remove moving averages (doesn't make sense anymore - all the data is moving average now) and contagious (because just one data point would remove contagious by the Singapura study).
